### PR TITLE
turned histogram python into proper pyd

### PR DESCRIPTION
**Pull request by klemens-morgenstern**
Damit da auch eine .pyd rauspurzelt und keine lib.

### CODE REVIEW

**Comment by klemens-morgenstern** [comment]
Alright, I added the Iterator-version with disable if, and thus removed boost::iterator_range. Should be a seperate PR, but I think that is a small change enough to be here.

**Comment by klemens-morgenstern** [comment]
The enable_if header moved between boost 1.55 and 1.61, that's why it won't work. I don't wanna fiddle around with your travis.yml, so maybe you could modify that to get a newer version (1.56 at the least) and then it will work. If you do so, I'll pull this into my branch and then we'll see if it works.

**Comment by HDembinski** [comment]
travis is a bit behind with boost, unfortunately. they provide a way to pull in a precompiled boost1.55 package, but nothing more recent than that. We can decide to drop using the boost package, and compile boost ourselves, then there is no problem in using the latest version. Using the package is convenient because it cuts down the compilation time, but it not necessary.

**Comment by klemens-morgenstern** [comment]
I know, funny enough that this is one version too early. The official boost library (and boost.process) pull the complete boost from github, so you know that the whole things works on the develop branch with all the other libraries before a release. But that causes horrible compile times.

Now, if I'd be able to get the python tests to run, the boost.build would automatically only compile the libraries you actually need, not all of it.

**Pull request merged**
