### PR TITLE
Remove build Serialization step as unnecessary

### PR DESCRIPTION
**Pull request by mloskot**
Serialization will be built automatically as part of test which requires the library as a dependency.

Add b2 command to build and run the speed tests.

### CODE REVIEW

**Comment by HDembinski** [comment]
The speed tests are not intended to be part of the CI tests, but I think it is cool if they can be build with b2.
However, you cannot run the speed tests without external libraries, therefore we should not list them in build.qbk or add a note that the speed tests require external libraries.

**Comment by mloskot** [comment]
I've removed the command from the docs. Sorry, I've only run the standalone `speed_cpp.cpp` test, missed the other require the third-parties.

**Comment by HDembinski** [comment]
Ok, merging! We could still just build the speed test.

**Comment by mloskot** [comment]
Good idea, done in #83

**Pull request merged**
